name: cvparser_b21_01
description: A application to parse cv's

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file_picker: ^4.6.1
  http: ^0.13.4
  flutter_svg: ^0.23.0+1
  get: ^4.6.5
  should_rebuild: ^1.0.1
  json_annotation: ^4.5.0
  file_saver: ^0.1.0
  flutter_dropzone: ^3.0.5
  cloud_firestore: ^3.2.1
  firebase_core: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
      - icons/pdf.svg
      - icons/icon.svg
      - icons/pdf_not_loaded.svg
  fonts:
    - family: Eczar
      fonts:
        - asset: fonts/Eczar/Eczar-Bold.ttf
        - asset: fonts/Eczar/Eczar-ExtraBold.ttf
        - asset: fonts/Eczar/Eczar-Medium.ttf
        - asset: fonts/Eczar/Eczar-Regular.ttf
        - asset: fonts/Eczar/Eczar-SemiBold.ttf
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather/Merriweather-Black.ttf
        - asset: fonts/Merriweather/Merriweather-Bold.ttf
        - asset: fonts/Merriweather/Merriweather-Light.ttf
        - asset: fonts/Merriweather/Merriweather-Regular.ttf
