name: Sonar Dev
on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Sonar Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=CV-Parser-develop
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_DEV_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}