// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyUaAdHlzgrYaYVxpfpZFEJuLcWSPnVOo',
    appId: '1:228944062100:web:401d34a55a5a0a447cf681',
    messagingSenderId: '228944062100',
    projectId: 'cv-parser-ca402',
    authDomain: 'cv-parser-ca402.firebaseapp.com',
    storageBucket: 'cv-parser-ca402.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByXzf-haD28Q6F6L17v9OoPiK4TdOlG94',
    appId: '1:228944062100:android:bc57df10879a54ea7cf681',
    messagingSenderId: '228944062100',
    projectId: 'cv-parser-ca402',
    storageBucket: 'cv-parser-ca402.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkFdwXOrhX8jUlyU-4XfRj2KHC_SFQP9w',
    appId: '1:228944062100:ios:d297ef11f42d01fe7cf681',
    messagingSenderId: '228944062100',
    projectId: 'cv-parser-ca402',
    storageBucket: 'cv-parser-ca402.appspot.com',
    iosClientId:
        '228944062100-5nb2lp06inhk42glnniskejaa3dg0bsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cvparserB2101',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkFdwXOrhX8jUlyU-4XfRj2KHC_SFQP9w',
    appId: '1:228944062100:ios:d297ef11f42d01fe7cf681',
    messagingSenderId: '228944062100',
    projectId: 'cv-parser-ca402',
    storageBucket: 'cv-parser-ca402.appspot.com',
    iosClientId:
        '228944062100-5nb2lp06inhk42glnniskejaa3dg0bsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cvparserB2101',
  );
}
