name: Preview Web

on:
  pull_request:
    branches: [ main ]
    types: [ open, synchronize ]

jobs:
  build:
    name: Preview Web
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo
        uses: actions/checkout@v2
      
      - name: Install flutter
        run: sudo snap install flutter --classic
      
      - name: Build for web
        run: flutter build web
      
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: cv-parser-ca402
